language: python
sudo: required
dist: xenial
matrix:
  include:
  - python: 3.6
    env: TOX_ENV=py36
  - python: 3.7
    env: TOX_ENV=py37
  - python: 3.8-dev
    env: TOX_ENV=py38
  - python: 3.6
    env: TOX_ENV=flake8
install:
- pip install tox coveralls
script:
- tox -e $TOX_ENV
before_cache:
- rm -rf $HOME/.cache/pip/log
cache:
  directories:
  - "$HOME/.cache/pip"
after_success:
- coveralls
