name: Unit Tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - PY_VER: py37
            python-version: 3.7
          - PY_VER: py38
            python-version: 3.8
          - PY_VER: py39
            python-version: 3.9
          - PY_VER: py310
            python-version: '3.10'
          - PY_VER: py311
            python-version: '3.11'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - name: Install test dependencies
        run: pip install tox coveralls

      # Runs a single command using the runners shell
      - name: Run tests
        run: |
          tox -e flake8;
          tox -e ${{matrix.PY_VER}};
